<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUHWyxp2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUHWyxp2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUHWyxp2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUHWyxp2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUHWyxp2\App_KernelDevDebugContainer([
    'container.build_hash' => 'UHWyxp2',
    'container.build_id' => '894d311d',
    'container.build_time' => 1738599649,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUHWyxp2');
