<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD2xVqFY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD2xVqFY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD2xVqFY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD2xVqFY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD2xVqFY\App_KernelDevDebugContainer([
    'container.build_hash' => 'D2xVqFY',
    'container.build_id' => 'fd55b7a5',
    'container.build_time' => 1739443444,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD2xVqFY');
